names = [
    "John Doe",
    "张三",
    "Lieschen Müller",
    "Max Mustermann",
    "Bilbo Beutlin",
    "Li Si",
    "Jan Janssen",
    "Juan Pérez",
    "Иван Иванов",
    "Fred Nurk",
    "Jean Dupont",
    "Ashok Kumar",
    "홍길동",
    "Jānis Bērziņš",
    "مجهول",
    "Juan dela Cruz",
    "Kovács János",
    "Người dấu tên",
    "Sade Vatandaş",
    "Petar Petrović",
    "名無しの権兵衛",
    "ישראל ישראל",
    "Meðal-Jón",
]